#!/bin/bash
set -e

echo "=============================="
echo " Hermes Agent"
echo "=============================="

echo "MODEL:"
echo "$OPENAI_MODEL"

echo "BASE:"
echo "$OPENAI_BASE_URL"

echo "KEY LENGTH:"
echo "${#OPENAI_API_KEY}"

mkdir -p /root/.hermes

envsubst < /tmp/config.yaml > /root/.hermes/config.yaml

echo "Hermes config installed"

echo "===== Config ====="
cat /root/.hermes/config.yaml
echo "=================="

mkdir -p /output

cd /opt/hermes-agent

echo "Running Hermes..."

RESULT=$(uv run hermes \
    -z "$@" \
) || true

echo "========== Hermes Result =========="
echo "$RESULT"
echo "==================================="

cat > /output/index.html <<EOF
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Hermes Generated News</title>

<style>
body {
    font-family:
    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    sans-serif;
    margin:40px;
    line-height:1.7;
}

pre {
    white-space:pre-wrap;
    word-break:break-word;
}
</style>

</head>

<body>

<h1>Hermes Generated News</h1>

<p>
Generated by Hermes Agent + NVIDIA API "$OPENAI_MODEL"
</p>

<hr>

<pre>
$RESULT
</pre>

</body>
</html>
EOF

chmod 644 /output/index.html

echo "Created file:"
ls -lh /output/index.html
