name: Hermes News Generator


on:

  workflow_dispatch:

  schedule:

    - cron: "0 */6 * * *"



permissions:

  contents: write



jobs:


  build:


    runs-on: ubuntu-latest

    timeout-minutes: 30



    steps:


    - name: Checkout repository

      uses: actions/checkout@v4

      with:

        fetch-depth: 0



    - name: Build Hermes Docker image

      run: |

        docker build \
          --progress=plain \
          -t hermes-agent .



    - name: Prepare output directory

      run: |

        mkdir -p output

        sudo chmod 777 output



    - name: Run Hermes

      env:

        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}

        OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}


      run: |


        echo "=================="

        echo "Running Hermes..."

        date


        timeout 25m docker run \
          --rm \
          -e OPENAI_API_KEY \
          -e OPENAI_BASE_URL \
          -e OPENAI_MODEL \
          -e HERMES_ACCEPT_HOOKS=1 \
          -v "$PWD/output:/output" \
          hermes-agent \
          "
          你现在对https://build.nvidia.com/models的所有模型进行总结，基于的的知识有点过时，你务必在线搜索资料对所有模型进行汇总。

          要求：

          1. 使用中文。
          2. 生成完整 HTML5 文件。
          3. 所有分析结果写入：/output/index.html

          不要修改其他文件。
          "


        echo "Hermes finished"

        date



    - name: Verify Hermes output

      run: |


        echo "===== output ====="

        ls -lah output


        if [ ! -f output/index.html ]; then

          echo "ERROR: output/index.html missing"

          exit 1

        fi


        if [ ! -s output/index.html ]; then

          echo "ERROR: index.html empty"

          exit 1

        fi


        echo "===== Preview ====="

        head -50 output/index.html



    - name: Fix output permission

      run: |


        sudo chown -R $USER:$USER output


        chmod 644 output/index.html



    - name: Commit only Hermes page

      run: |


        git config user.name "github-actions[bot]"


        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"



        git add output/index.html



        if git diff --cached --quiet; then

          echo "No changes"

          exit 0

        fi



        git commit \
          -m "Update Hermes generated news"



        git pull --rebase origin ${GITHUB_REF_NAME}



        git push origin HEAD:${GITHUB_REF_NAME}
