name: Hermes Agent

on:
  workflow_dispatch:

  # 如果想定时运行，取消注释
  # schedule:
  #   - cron: "0 */6 * * *"


jobs:
  hermes:

    runs-on: ubuntu-latest

    timeout-minutes: 360

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Check system
      run: |
        uname -a
        docker version
        free -h
        df -h


    - name: Build Hermes image
      run: |
        docker build \
          -t hermes-agent .


    - name: Run Hermes
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

      run: |

        docker run \
          --rm \
          -e OPENAI_API_KEY \
          -e ANTHROPIC_API_KEY \
          hermes-agent
